### PR TITLE
Using ProjectTo from AutoMapper

### PR DESCRIPTION
**Pull request by AlbertoMonteiro**

### CODE REVIEW

**Comment by thiagolunardi** [comment]
Hey, I have two question. :)

What's the benefits of using `ProjectTo` instead of general `Map` with AutoMapper?

And why to expose the Repository with `IQueryable`?

**Comment by khaueviana** [comment]
I have this question too hehe

**Comment by AlbertoMonteiro** [comment]
Hi @thiagolunardi and @khaueviana!!

Let me ask something first, whats the problem of exposing `IQueryable`?

--------------------------

`ProjectTo` is an extension method of `IQueryable` that is owned by AutoMapper, and the benefits from using this instead regular `Map`, is: 

> When using an ORM such as NHibernate or Entity Framework with AutoMapper's standard `Mapper.Map` functions, you may notice that the ORM will query all the fields of all the objects within a graph when AutoMapper is attempting to map the results to a destination type.
> 
> If your ORM exposes `IQueryable`s, you can use AutoMapper's QueryableExtensions helper methods to address this key pain.
> 
> The `.ProjectTo<Type>()` will tell AutoMapper's mapping engine to emit a `select` clause to the IQueryable that will inform entity framework that it only needs to query only the columns of that you have in your ViewModel, same as if you manually projected your `IQueryable` to an `ViewModel` with a `Select` clause. 

So you have a better performance in your database, and also in the pipeline of the EF that materialize the result of database in your classes. There is no tracking, no proxy. So, faster query, fast materialization, faster response.

If you have more question about `ProjectTo`, see this https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions

**Comment by thiagolunardi** [comment]
Ok, I got it. 
May be a way. My concern is just that to expose the repo in a way that somewhere could make a badquery.

For the last, while removed the `Find()` with `AsNoTracking()`? 
Isn't this good for performance?

**Comment by AlbertoMonteiro** [comment]
> My concern is just that to expose the repo in a way that somewhere could make a badquery.

GetAll returning an IEnumerable, still let you make a query, but this one, will run in web server, instead of database, and this is a aslo a bad query in most of cases.

Let's see this example, my GetAll method return IEnumerable:
`GetAll().Where(s => s.Something = 10)` is worst than if you return an IQueryable, because DB will handle this.

But again, we have a problem, in most of cases if you add any kind of Query (Linq to Sql/Entities ou Linq to Object) is bad, because this is a responsability of Repository.

So exposing a Find method that receive an expression in the Repository, is a break in SRP(Single Responsability Principle).

> For the last, while removed the `Find()` with `AsNoTracking()`?

It dependes, if I need to change any value of the Entity and than save, I should **not** use AsNoTracking, but if I need **only read** the values, sure, I must use AsNoTracking for better performance.

Another tip, the previous GetAll method, return a List<Entity> as a IEnumerable, most probably you wont change this list, either add something to it, so you should use `ToArray()`, because Array api dificult to do any kind of change in the array than a List api, and Array is cheaper than List when talking about memory.

**Comment by khaueviana** [comment]
Humm, nicee!

But exposing IQueryable you can still make filters out of the Repository. Are not you still breaking the SRP?

What's the difference between exposing IQueryable (besides the performance issue) and removing Predicates?

**Comment by AlbertoMonteiro** [comment]
> But exposing IQueryable you can still make filters out of the Repository

Yes

> Are not you still breaking the SRP?

Yes

--------------

But exposing IEnumerable, you can still make filters, the difference between them, is, the filter will execute on database or in web server?
So, using IEnumerable, doesn't protect you to break the SRP.

Code review can check this, and request changes!!!!

-----------

> What's the difference between exposing IQueryable (besides the performance issue) and removing Predicates?

This one I will anwser in portuguese.
Removendo o predicado da API do repositório, é uma forma de dizer que ele é quem tem que ser o cara que sabe fazer os filtros, e te retornar tudo pronto.
E como eu falei na resposta acima, usar o IEnumerable, te permite ainda fazer filtros, e isso por si só, se for feito é uma quebra do SRP.

Então a proposta de usar o IQueryable em detrimento do IEnumerable, é mais pelo fato de poder usufruir do ProjetoTo.

Obrigado pelos seus questionamentos, é um prazer poder discutir com vocês.

**Comment by pedrobenevides** [comment]
I agree with @AlbertoMonteiro , and another thing to concern with the use of `IQueryable` is that it not fetch the data until you needed, so, you can have fewer unnecessary queries hitting your database.

**Comment by EduardoPires** [comment]
Thank you for contribution and explanation

**Comment by AlbertoMonteiro** [comment]
It was a pleasure @EduardoPires

**Pull request merged**
