### PR TITLE
Angular 6 WebApp

### PR DESCRIPTION
**Pull request by brunohbrito**
## Adding an Angular 5 WebApp
- Lazy loaded modules
- guard
- integrated with WebApi
- Translation feature

### WebApi
- Identity and authorization features, like Asp.net mvc
- Reset password
- Profile manager

### Bug fixes
- Minor bug fixes
- Some new instruction at README.md

image
image
image
image
image

### CODE REVIEW

**Comment by rc201612** [comment]
Hi, 

Awesome work!! 

Is there any way you can get this to run from within Visual Studio? I have tried to build but cannot get it to hit services. Database has been created and exists, etc. 

Thanks,

**Comment by nicotravassos** [comment]
Just wow! I really hope @EduardoPires  accepts this and merges it!

**Comment by nicotravassos** [comment]
@brunohbrito Do you have plans of adding this theme to the main Equinox.UI.Web?

**Comment by brunohbrito** [comment]
Hi @rc201612,

You need to run both of projects:

Open visual studio, set Equinox.WebApi as main project, then run it.

Start visual studio code and open folder Equinox.WebApp, so open terminal  and type npm install and npm start!

**Comment by brunohbrito** [comment]
@nicotravassos 

I'm not sure about it at this moment, because I'm working at a WebApi with Token Auth, JWT and asap make available google and facebook integration.

Who knows in near feature!

**Comment by nicotravassos** [comment]
@brunohbrito 

maybe add to this example listing of customers like http://equinoxproject.azurewebsites.net/ also giving the user ability of adding, editing, deleting and view history listed customer. I dunno just an Idea that makes sense to make it function like the original http://equinoxproject.azurewebsites.net/ with a better theme etc

**Comment by brunohbrito** [comment]
@TeoDanilo 

I'm not sure that you can run both of projects inside Vs2007, after all you need to run angular-cli to start the app at the same time you need to start Equinox.WebApi.

There is a similar question here: https://stackoverflow.com/questions/44530354/running-visual-studio-2017-with-angular-4-and-angular-cli maybe it'll help you!

There are few blogs and people saying that you can do it, but nothing detailed.

And I strongly recommend that you start from simple: Use Vs Code to run angular-cli applications, there are several examples and support, in the beggining may youl feel yourself unconfortable, but after 2 or 3 hours you'll be like a Jedi

@nicotravassos 

I'll provide these features!

**Comment by nicotravassos** [comment]
@brunohbrito 

Music to my ears thank you.

**Comment by TeoDanilo** [comment]
@brunohbrito 

Is the "Upload new picture" feature working? I get an error message pop up and nothing happens

**Comment by brunohbrito** [comment]
@TeoDanilo

Yes, It's working!! 

To get it working you'll net set your appsettings with azure blob credentials

image

image

**Comment by rc201612** [comment]
@brunohbrito - Thanks. I have managed to get that running. 

One more thing: after logging in, which it does successfully, I am not navigated away to the dashboard. Should this happen? It is just staying on the login screen.

Thanks,

**Comment by TeoDanilo** [comment]
@brunohbrito 

As i'm not familiarized with Angular yet, I'm using your sample (hope you don't mind) with this theme you're using (I have bought it a year ago) to do exactly the same thing as you but on the Equinox.UI.Site just to practice. If you whant I can share with you, then you can provide this theme both in Angular and MVC. (We still need to wait Eduardo show his face around here and give us some info about what he is doing and gonna to do)

**Comment by brunohbrito** [comment]
Sorry, I was off these days, too much work.

@TeoDanilo I'll try to change the UI oy mvc project!

@rc201612 I did it 'cause the project that I'm working the user needs to confirm his e-mail first, but there is no reason to do this in Equinox, I'll change it.

**Comment by brunohbrito** [comment]
Merged

**Comment by rc201612** [comment]
Hi @brunohbrito ,

Is there any intention to update this to Angular 6?

Thanks

**Comment by brunohbrito** [comment]
Updated to agular6

**Pull request closed without merging**
